### ISSUE TITLE
Crashes on Tiramisu

### ISSUE THREAD

**Issue by msfjarvis** [msfjarvis/compose-lobsters#317]
```
AndroidRuntime  E  FATAL EXCEPTION: main
                E  Process: dev.msfjarvis.claw.android, PID: 20099
                E  java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/OnBackInvokedCallback;
                E      at androidx.activity.ComponentActivity.<init>(ComponentActivity.java:150)
                E      at dev.msfjarvis.claw.android.Hilt_MainActivity.<init>(Hilt_MainActivity.java:27)
                E      at dev.msfjarvis.claw.android.MainActivity.<init>(MainActivity.kt:24)
                E      at java.lang.Class.newInstance(Native Method)
                E      at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
                E      at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
                E      at android.app.Instrumentation.newActivity(Instrumentation.java:1283)
                E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3572)
                E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3816)
                E      at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:99)
                E      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                E      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2299)
                E      at android.os.Handler.dispatchMessage(Handler.java:106)
                E      at android.os.Looper.loopOnce(Looper.java:201)
                E      at android.os.Looper.loop(Looper.java:288)
                E      at android.app.ActivityThread.main(ActivityThread.java:7844)
                E      at java.lang.reflect.Method.invoke(Native Method)
                E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                E  Caused by: java.lang.ClassNotFoundException: android.view.OnBackInvokedCallback
                E      ... 20 more
```

**Comment by msfjarvis** [comment]
Still crashes in the comments page

**Comment by msfjarvis** [comment]
Fixed by https://msfjarvis.dev/g/compose-lobsters/cd6948f5fe3d
