### ISSUE TITLE
Error - Failed to load post

### ISSUE THREAD

**Issue by soo-shan** [msfjarvis/compose-lobsters#491]
Getting below error on opening the app. 

```
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 399: Expected start of the object '{', but had '"' instead at path: $[0].submitter_user
JSON input: .....r_languages","submitter_user":"eatonphil","user_is_author":t.....
	at io.sentry.protocol.DebugMeta.JsonDecodingException(SourceFile:2)
	at io.sentry.protocol.DebugMeta.JsonDecodingException(SourceFile:4)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(Unknown Source:58)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(Unknown Source:12)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(Unknown Source:72)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(Unknown Source:47)
	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(SourceFile:7)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(Unknown Source:42)
	at dev.msfjarvis.claw.model.User$$serializer.deserialize(Unknown Source:7)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(Unknown Source:103)
	at androidx.compose.ui.unit.DpKt.decodeSerializableValue(Unknown Source:5)
	at androidx.compose.ui.unit.DpKt.decodeSerializableElement(Unknown Source:10)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(Unknown Source:49)
	at dev.msfjarvis.claw.model.LobstersPost$$serializer.deserialize(Unknown Source:58)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(Unknown Source:103)
	at androidx.compose.ui.unit.DpKt.decodeSerializableValue(Unknown Source:5)
	at androidx.compose.ui.unit.DpKt.decodeSerializableElement(Unknown Source:10)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(Unknown Source:49)
	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(Unknown Source:7)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(Unknown Source:34)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(Unknown Source:5)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(Unknown Source:103)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(Unknown Source:50)
	at com.slack.eithernet.ApiResultConverterFactory$ApiResultConverter.convert(Unknown Source:9)
	at retrofit2.OkHttpCall.parseResponse(Unknown Source:53)
	at retrofit2.OkHttpCall$1.onResponse(Unknown Source:4)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(Unknown Source:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


```

Version: 1.41.0
Installed via IzzyOnDroid fdroid repo

**Comment by msfjarvis** [comment]
Lobsters changed their API response which caused some breakage, I've released a new build but it might take a few hours for IzzyOnDroid and Google Play to pick it up https://github.com/msfjarvis/compose-lobsters/releases/tag/v1.42.0

**Comment by soo-shan** [comment]
@msfjarvis seems like something broke again

```
java.io.IOException: API returned an invalid response
	at dev.msfjarvis.claw.android.paging.LobstersPagingSource.load(Unknown Source:372)
	at dev.msfjarvis.claw.android.paging.LobstersPagingSource$load$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:114)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```

**Comment by msfjarvis** [comment]
_sigh_ 

I'll take a look, thanks for letting me know.

**Comment by msfjarvis** [comment]
Seems like Lobsters itself is down? I can't get the website to load on my end.

**Comment by soo-shan** [comment]
Yeah, I'm also not able to directly go to https://lobste.rs/

**Comment by msfjarvis** [comment]
That'd explain it then. Either way, I'll improve the error reporting around this to make it more obvious when Lobsters is having issues.
